### ISSUE TITLE
Failed tests: testInterruptibility (org.archive.util.InterruptibleCharSequenceTest): exception not throw

### ISSUE THREAD

**Issue by cronopioelectronico** [commoncrawl/ia-web-commons#25]
Hi,

when installing through:
```
git clone https://github.com/commoncrawl/ia-web-commons
cd ia-web-commons
mvn install 
```
I get the error:

`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project ia-web-commons: There are test failures.`

and the following content of the file `target/surefire-reports/org.archive.util.InterruptibleCharSequenceTest.txt`
```
-------------------------------------------------------------------------------
Test set: org.archive.util.InterruptibleCharSequenceTest
-------------------------------------------------------------------------------
Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.509 sec <<< FAILURE!
testInterruptibility(org.archive.util.InterruptibleCharSequenceTest)  Time elapsed: 0.508 sec  <<< FAILURE!
junit.framework.AssertionFailedError: exception not thrown
        at junit.framework.Assert.fail(Assert.java:47)
        at junit.framework.Assert.assertTrue(Assert.java:20)
        at org.archive.util.InterruptibleCharSequenceTest.testInterruptibility(InterruptibleCharSequenceTest.java:118)
```

I am trying the installation on the following system:

- 5.8.0-36-generic 40~20.04.1-Ubuntu
- java --version
openjdk 11.0.10 2021-01-19
OpenJDK Runtime Environment (build 11.0.10+9-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.10+9-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)
- javac 11.0.10
- Apache Maven 3.6.3
Maven home: /usr/share/maven
Java version: 11.0.10, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_GB, platform encoding: UTF-8
OS name: "linux", version: "5.8.0-36-generic", arch: "amd64", family: "unix"

Thanks!

**Comment by sebastian-nagel** [comment]
Hi @cronopioelectronico, thanks for the bug report! I'm able to reproduce the failing unit test using Java 11. I'll have a look. Note: using Java 8 all tests pass.

**Comment by cronopioelectronico** [comment]
Great, thanks for replying so fast @sebastian-nagel!

**Comment by sebastian-nagel** [comment]
Hi @cronopioelectronico, the reason was trivial: the unit test was based on the assumption that after 500ms the matching thread was still running. Looks like there are some performance improvements and running a thread and do the matching takes less than 32ms on JDK 11 (on my hardware):
```
Running org.archive.util.InterruptibleCharSequenceTest
already done, retrying with shorter sleep time: 256ms
already done, retrying with shorter sleep time: 128ms
already done, retrying with shorter sleep time: 64ms
already done, retrying with shorter sleep time: 32ms
already done, retrying with shorter sleep time: 16ms
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.013 sec
```
See 8accf19 for more details. Please update and retry to build. Thanks again!

**Comment by cronopioelectronico** [comment]
Works like a charm @sebastian-nagel, thanks!
