### ISSUE TITLE
data-href not captured in WAT 'Links' metadata

### ISSUE THREAD

**Issue by e271828-** [commoncrawl/ia-web-commons#7]
As per conversation with Sebastian:

Currently, a major class of link is not captured in metadata. Example:

`div class="fb-video" data-href="https://www.facebook.com/facebook/videos/10153231379946729/" data-width="500" data-show-text="false"
`

This format is frequently used for e.g. embedded video.

**Comment by sebastian-nagel** [comment]
The `fb-video` links are part of [Facebook's social plugins](https://developers.facebook.com/docs/plugins/). A solution should include the other Facebook plugins, and be extensible to social links pointing to other networks (Google+, Twitter, etc.)

**Comment by e271828-** [comment]
`data-href` is also widely used beyond those social platforms. For example, some CMS systems and jQuery plugins also generate JS-driven links of the format `div data-href="link"` for navbars etc. I'd thus expect an increase in crawl depth, but this is easy enough to test.

**Comment by e271828-** [comment]
Various examples attached.

[data-href.examples.html.zip](https://github.com/commoncrawl/ia-web-commons/files/781376/data-href.examples.html.zip)

**Comment by sebastian-nagel** [comment]
Thanks, @e271828-! The data-href links should be included already in the WAT files of the February crawl.
